wireguard_interface: wg0
wireguard_group: servers
wireguard_packages:
  - wireguard
wireguard_config_dir: /etc/wireguard
wireguard_private_key_file: /etc/wireguard/privatekey
wireguard_public_key_file: /etc/wireguard/publickey
wireguard_config_file: "/etc/wireguard/{{ wireguard_interface }}.conf"
wireguard_listen_port: "{{ wireguard_port }}"
wireguard_persistent_keepalive: 25
wireguard_enable_ip_forwarding: false
